package fr.shadcanard.fbm.world.village;

import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.world.gen.structure.StructureBoundingBox;
import net.minecraft.world.gen.structure.StructureComponent;
import net.minecraft.world.gen.structure.StructureVillagePieces;

import java.util.List;
import java.util.Random;

public class ComponentSeasonOne extends StructureVillagePieces.House1 {
    private int averageGroundLevel = -1;

    public ComponentSeasonOne(){

    }

    public ComponentSeasonOne(StructureVillagePieces.Start villagePiece, int par2, Random par3random, StructureBoundingBox par4StructureBoundingBox, int par5){
        super();
        this.coordBaseMode = par5;
        this.boundingBox = par4StructureBoundingBox;
    }

    public static ComponentSeasonOne buildComponent (StructureVillagePieces.Start villagePiece, List pieces, Random random, int p1, int p2, int p3, int p4, int p5){
        StructureBoundingBox structureBoundingBox = StructureBoundingBox.getComponentToAddBoundingBox(p1,p2,p3,0,0,0,12,6,13,p4);
        return canVillageGoDeeper(structureBoundingBox) && StructureComponent.findIntersecting(pieces, structureBoundingBox) == null ? new ComponentSeasonOne(villagePiece, p5, random, structureBoundingBox, p4) : null;
    }

    @Override
    public boolean addComponentParts(World world, Random random, StructureBoundingBox structureBoundingBox) {
        if (this.averageGroundLevel < 0){
            this.averageGroundLevel = this.getAverageGroundLevel(world,structureBoundingBox);
            if (this.averageGroundLevel < 0){
                return true;
            }

            this.boundingBox.offset(0,this.averageGroundLevel - this.boundingBox.maxY + 6, 0);
        }

        //first level
        world.setBlock(0, 0, 0, Blocks.grass);
        world.setBlock(1, 0, 0, Blocks.grass);
        world.setBlock(2, 0, 0, Blocks.grass);
        world.setBlock(3, 0, 0, Blocks.grass);
        world.setBlock(4, 0, 0, Blocks.grass);
        world.setBlock(5, 0, 0, Blocks.grass);
        world.setBlock(6, 0, 0, Blocks.grass);
        world.setBlock(7, 0, 0, Blocks.grass);
        world.setBlock(8, 0, 0, Blocks.grass);
        world.setBlock(9, 0, 0, Blocks.grass);
        world.setBlock(10, 0, 0, Blocks.grass);
        world.setBlock(11, 0, 0, Blocks.grass);
        world.setBlock(0, 0, 1, Blocks.grass);
        world.setBlock(1, 0, 1, Blocks.grass);
        world.setBlock(2, 0, 1, Blocks.dirt);
        world.setBlock(3, 0, 1, Blocks.cobblestone);
        world.setBlock(4, 0, 1, Blocks.cobblestone);
        world.setBlock(5, 0, 1, Blocks.cobblestone);
        world.setBlock(6, 0, 1, Blocks.cobblestone);
        world.setBlock(7, 0, 1, Blocks.cobblestone);
        world.setBlock(8, 0, 1, Blocks.cobblestone);
        world.setBlock(9, 0, 1, Blocks.cobblestone);
        world.setBlock(10, 0, 1, Blocks.cobblestone);
        world.setBlock(11, 0, 1, Blocks.grass);
        world.setBlock(0, 0, 2, Blocks.grass);
        world.setBlock(1, 0, 2, Blocks.grass);
        world.setBlock(2, 0, 2, Blocks.cobblestone);
        world.setBlock(3, 0, 2, Blocks.planks);
        world.setBlock(4, 0, 2, Blocks.planks);
        world.setBlock(5, 0, 2, Blocks.planks);
        world.setBlock(6, 0, 2, Blocks.double_stone_slab);
        world.setBlock(7, 0, 2, Blocks.double_stone_slab);
        world.setBlock(8, 0, 2, Blocks.double_stone_slab);
        world.setBlock(9, 0, 2, Blocks.double_stone_slab);
        world.setBlock(10, 0, 2, Blocks.cobblestone);
        world.setBlock(11, 0, 2, Blocks.gravel);
        world.setBlock(0, 0, 3, Blocks.grass);
        world.setBlock(1, 0, 3, Blocks.double_stone_slab);
        world.setBlock(2, 0, 3, Blocks.cobblestone);
        world.setBlock(3, 0, 3, Blocks.planks);
        world.setBlock(4, 0, 3, Blocks.planks);
        world.setBlock(5, 0, 3, Blocks.planks);
        world.setBlock(6, 0, 3, Blocks.double_stone_slab);
        world.setBlock(7, 0, 3, Blocks.double_stone_slab);
        world.setBlock(8, 0, 3, Blocks.double_stone_slab);
        world.setBlock(9, 0, 3, Blocks.crafting_table /* Workbench */ );
        world.setBlock(10, 0, 3, Blocks.double_stone_slab);
        world.setBlock(11, 0, 3, Blocks.gravel);
        world.setBlock(0, 0, 4, Blocks.grass);
        world.setBlock(1, 0, 4, Blocks.water);
        world.setBlock(2, 0, 4, Blocks.cobblestone);
        world.setBlock(3, 0, 4, Blocks.planks);
        world.setBlock(4, 0, 4, Blocks.planks);
        world.setBlock(5, 0, 4, Blocks.planks);
        world.setBlock(6, 0, 4, Blocks.double_stone_slab);
        world.setBlock(7, 0, 4, Blocks.double_stone_slab);
        world.setBlock(8, 0, 4, Blocks.double_stone_slab);
        world.setBlock(9, 0, 4, Blocks.crafting_table);
        world.setBlock(10, 0, 4, Blocks.double_stone_slab);
        world.setBlock(11, 0, 4, Blocks.gravel);
        world.setBlock(0, 0, 5, Blocks.grass);
        world.setBlock(1, 0, 5, Blocks.water);
        world.setBlock(2, 0, 5, Blocks.cobblestone);
        world.setBlock(3, 0, 5, Blocks.planks);
        world.setBlock(4, 0, 5, Blocks.planks);
        world.setBlock(5, 0, 5, Blocks.planks);
        world.setBlock(6, 0, 5, Blocks.double_stone_slab);
        world.setBlock(7, 0, 5, Blocks.double_stone_slab);
        world.setBlock(8, 0, 5, Blocks.double_stone_slab);
        world.setBlock(9, 0, 5, Blocks.double_stone_slab);
        world.setBlock(10, 0, 5, Blocks.cobblestone);
        world.setBlock(11, 0, 5, Blocks.gravel);
        world.setBlock(0, 0, 6, Blocks.grass);
        world.setBlock(1, 0, 6, Blocks.double_stone_slab);
        world.setBlock(2, 0, 6, Blocks.cobblestone);
        world.setBlock(3, 0, 6, Blocks.planks);
        world.setBlock(4, 0, 6, Blocks.planks);
        world.setBlock(5, 0, 6, Blocks.planks);
        world.setBlock(6, 0, 6, Blocks.cobblestone);
        world.setBlock(7, 0, 6, Blocks.cobblestone);
        world.setBlock(8, 0, 6, Blocks.cobblestone);
        world.setBlock(9, 0, 6, Blocks.cobblestone);
        world.setBlock(10, 0, 6, Blocks.cobblestone);
        world.setBlock(11, 0, 6, Blocks.grass);
        world.setBlock(0, 0, 7, Blocks.grass);
        world.setBlock(1, 0, 7, Blocks.grass);
        world.setBlock(2, 0, 7, Blocks.cobblestone);
        world.setBlock(3, 0, 7, Blocks.chest);
        world.setBlockMetadataWithNotify(3, 0, 7, 5, 5);
        world.setBlock(4, 0, 7, Blocks.planks);
        world.setBlock(5, 0, 7, Blocks.planks);
        world.setBlock(6, 0, 7, Blocks.cobblestone);
        world.setBlock(7, 0, 7, Blocks.grass);
        world.setBlock(8, 0, 7, Blocks.grass);
        world.setBlock(9, 0, 7, Blocks.grass);
        world.setBlock(10, 0, 7, Blocks.grass);
        world.setBlock(11, 0, 7, Blocks.grass);
        world.setBlock(0, 0, 8, Blocks.grass);
        world.setBlock(1, 0, 8, Blocks.grass);
        world.setBlock(2, 0, 8, Blocks.cobblestone);
        world.setBlock(3, 0, 8, Blocks.chest);
        world.setBlockMetadataWithNotify(3, 0, 8, 5, 5);
        world.setBlock(4, 0, 8, Blocks.planks);
        world.setBlock(5, 0, 8, Blocks.planks);
        world.setBlock(6, 0, 8, Blocks.cobblestone);
        world.setBlock(7, 0, 8, Blocks.grass);
        world.setBlock(8, 0, 8, Blocks.grass);
        world.setBlock(9, 0, 8, Blocks.grass);
        world.setBlock(10, 0, 8, Blocks.grass);
        world.setBlock(11, 0, 8, Blocks.grass);
        world.setBlock(0, 0, 9, Blocks.grass);
        world.setBlock(1, 0, 9, Blocks.grass);
        world.setBlock(2, 0, 9, Blocks.cobblestone);
        world.setBlock(3, 0, 9, Blocks.planks);
        world.setBlock(4, 0, 9, Blocks.planks);
        world.setBlock(5, 0, 9, Blocks.planks);
        world.setBlock(6, 0, 9, Blocks.cobblestone);
        world.setBlock(7, 0, 9, Blocks.grass);
        world.setBlock(8, 0, 9, Blocks.grass);
        world.setBlock(9, 0, 9, Blocks.grass);
        world.setBlock(10, 0, 9, Blocks.grass);
        world.setBlock(11, 0, 9, Blocks.grass);
        world.setBlock(0, 0, 10, Blocks.grass);
        world.setBlock(1, 0, 10, Blocks.grass);
        world.setBlock(2, 0, 10, Blocks.cobblestone);
        world.setBlock(3, 0, 10, Blocks.cobblestone);
        world.setBlock(4, 0, 10, Blocks.cobblestone);
        world.setBlock(5, 0, 10, Blocks.cobblestone);
        world.setBlock(6, 0, 10, Blocks.cobblestone);
        world.setBlock(7, 0, 10, Blocks.grass);
        world.setBlock(8, 0, 10, Blocks.grass);
        world.setBlock(9, 0, 10, Blocks.grass);
        world.setBlock(10, 0, 10, Blocks.grass);
        world.setBlock(11, 0, 10, Blocks.grass);
        world.setBlock(0, 0, 11, Blocks.grass);
        world.setBlock(1, 0, 11, Blocks.grass);
        world.setBlock(2, 0, 11, Blocks.grass);
        world.setBlock(3, 0, 11, Blocks.grass);
        world.setBlock(4, 0, 11, Blocks.grass);
        world.setBlock(5, 0, 11, Blocks.grass);
        world.setBlock(6, 0, 11, Blocks.grass);
        world.setBlock(7, 0, 11, Blocks.grass);
        world.setBlock(8, 0, 11, Blocks.grass);
        world.setBlock(9, 0, 11, Blocks.grass);
        world.setBlock(10, 0, 11, Blocks.grass);
        world.setBlock(11, 0, 11, Blocks.grass);
        world.setBlock(0, 0, 12, Blocks.grass);
        world.setBlock(1, 0, 12, Blocks.grass);
        world.setBlock(2, 0, 12, Blocks.grass);
        world.setBlock(3, 0, 12, Blocks.grass);
        world.setBlock(4, 0, 12, Blocks.grass);
        world.setBlock(5, 0, 12, Blocks.grass);
        world.setBlock(6, 0, 12, Blocks.grass);
        world.setBlock(7, 0, 12, Blocks.grass);
        world.setBlock(8, 0, 12, Blocks.grass);
        world.setBlock(9, 0, 12, Blocks.grass);
        world.setBlock(10, 0, 12, Blocks.grass);
        world.setBlock(11, 0, 12, Blocks.grass);
        world.setBlock(1, 1, 0, Blocks.fence);
        world.setBlock(2, 1, 0, Blocks.fence);
        world.setBlock(3, 1, 0, Blocks.fence);
        world.setBlock(4, 1, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(4, 1, 0, 2, 2);
        world.setBlock(5, 1, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(5, 1, 0, 2, 2);
        world.setBlock(6, 1, 0, Blocks.fence);
        world.setBlock(7, 1, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(7, 1, 0, 2, 2);
        world.setBlock(8, 1, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(8, 1, 0, 2, 2);
        world.setBlock(9, 1, 0, Blocks.fence);
        world.setBlock(10, 1, 0, Blocks.fence);
        world.setBlock(11, 1, 0, Blocks.fence);
        world.setBlock(1, 1, 1, Blocks.fence);
        world.setBlock(2, 1, 1, Blocks.cobblestone);
        world.setBlock(3, 1, 1, Blocks.cobblestone);
        world.setBlock(4, 1, 1, Blocks.cobblestone);
        world.setBlock(5, 1, 1, Blocks.cobblestone);
        world.setBlock(6, 1, 1, Blocks.cobblestone);
        world.setBlock(7, 1, 1, Blocks.cobblestone);
        world.setBlock(8, 1, 1, Blocks.cobblestone);
        world.setBlock(9, 1, 1, Blocks.cobblestone);
        world.setBlock(10, 1, 1, Blocks.cobblestone);
        world.setBlock(11, 1, 1, Blocks.fence);
        world.setBlock(1, 1, 2, Blocks.fence);
        world.setBlock(2, 1, 2, Blocks.cobblestone);
        world.setBlock(3, 1, 2, Blocks.log);
        world.setBlock(5, 1, 2, Blocks.wall_sign);
        world.setBlockMetadataWithNotify(5, 1, 2, 4, 4);
        world.setBlock(6, 1, 2, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(6, 1, 2, 3, 3);
        world.setBlock(7, 1, 2, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(7, 1, 2, 3, 3);
        world.setBlock(8, 1, 2, Blocks.wall_sign);
        world.setBlockMetadataWithNotify(8, 1, 2, 5, 5);
        world.setBlock(9, 1, 2, Blocks.bookshelf);
        world.setBlock(10, 1, 2, Blocks.cobblestone);
        world.setBlock(11, 1, 2, Blocks.fence);
        world.setBlock(1, 1, 3, Blocks.stone_slab);
        world.setBlock(2, 1, 3, Blocks.cobblestone);
        world.setBlock(3, 1, 3, Blocks.stone);
        world.setBlock(10, 1, 3, Blocks.wooden_door);
        world.setBlockMetadataWithNotify(10, 1, 3, 2, 2);
        world.setBlock(2, 1, 4, Blocks.cobblestone);
        world.setBlock(3, 1, 4, Blocks.furnace);
        world.setBlockMetadataWithNotify(3, 1, 4, 5, 5);
        world.setBlock(10, 1, 4, Blocks.wooden_door);
        world.setBlockMetadataWithNotify(10, 1, 4, 2, 2);
        world.setBlock(2, 1, 5, Blocks.cobblestone);
        world.setBlock(3, 1, 5, Blocks.log);
        world.setBlock(6, 1, 5, Blocks.bookshelf);
        world.setBlock(7, 1, 5, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(7, 1, 5, 2, 2);
        world.setBlock(8, 1, 5, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(8, 1, 5, 2, 2);
        world.setBlock(9, 1, 5, Blocks.bookshelf);
        world.setBlock(10, 1, 5, Blocks.cobblestone);
        world.setBlock(11, 1, 5, Blocks.fence);
        world.setBlock(1, 1, 6, Blocks.stone_slab);
        world.setBlock(2, 1, 6, Blocks.cobblestone);
        world.setBlock(6, 1, 6, Blocks.cobblestone);
        world.setBlock(7, 1, 6, Blocks.cobblestone);
        world.setBlock(8, 1, 6, Blocks.cobblestone);
        world.setBlock(9, 1, 6, Blocks.cobblestone);
        world.setBlock(10, 1, 6, Blocks.cobblestone);
        world.setBlock(11, 1, 6, Blocks.fence);
        world.setBlock(1, 1, 7, Blocks.stone_stairs);
        world.setBlock(2, 1, 7, Blocks.cobblestone);
        world.setBlock(4, 1, 7, Blocks.stone_slab);
        world.setBlockMetadataWithNotify(4, 1, 7, 7, 7);
        world.setBlock(5, 1, 7, Blocks.stone_slab);
        world.setBlockMetadataWithNotify(5, 1, 7, 7, 7);
        world.setBlock(6, 1, 7, Blocks.cobblestone);
        world.setBlock(7, 1, 7, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(7, 1, 7, 3, 3);
        world.setBlock(8, 1, 7, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(8, 1, 7, 3, 3);
        world.setBlock(9, 1, 7, Blocks.fence);
        world.setBlock(10, 1, 7, Blocks.fence);
        world.setBlock(11, 1, 7, Blocks.fence);
        world.setBlock(1, 1, 8, Blocks.stone_stairs);
        world.setBlock(2, 1, 8, Blocks.cobblestone);
        world.setBlock(4, 1, 8, Blocks.stone_slab);
        world.setBlockMetadataWithNotify(4, 1, 8, 7, 7);
        world.setBlock(5, 1, 8, Blocks.stone_slab);
        world.setBlockMetadataWithNotify(5, 1, 8, 7, 7);
        world.setBlock(6, 1, 8, Blocks.cobblestone);
        world.setBlock(7, 1, 8, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(7, 1, 8, 1, 1);
        world.setBlock(1, 1, 9, Blocks.fence);
        world.setBlock(2, 1, 9, Blocks.cobblestone);
        world.setBlock(3, 1, 9, Blocks.bookshelf);
        world.setBlock(4, 1, 9, Blocks.wool);
        world.setBlockMetadataWithNotify(4, 1, 9, 10, 10);
        world.setBlock(5, 1, 9, Blocks.wool);
        world.setBlockMetadataWithNotify(5, 1, 9, 10, 10);
        world.setBlock(6, 1, 9, Blocks.cobblestone);
        world.setBlock(7, 1, 9, Blocks.fence);
        world.setBlock(1, 1, 10, Blocks.fence);
        world.setBlock(2, 1, 10, Blocks.cobblestone);
        world.setBlock(3, 1, 10, Blocks.cobblestone);
        world.setBlock(4, 1, 10, Blocks.cobblestone);
        world.setBlock(5, 1, 10, Blocks.cobblestone);
        world.setBlock(6, 1, 10, Blocks.cobblestone);
        world.setBlock(7, 1, 10, Blocks.fence);
        world.setBlock(1, 1, 11, Blocks.fence);
        world.setBlock(2, 1, 11, Blocks.fence);
        world.setBlock(3, 1, 11, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(3, 1, 11, 3, 3);
        world.setBlock(4, 1, 11, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(4, 1, 11, 3, 3);
        world.setBlock(5, 1, 11, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(5, 1, 11, 3, 3);
        world.setBlock(6, 1, 11, Blocks.fence);
        world.setBlock(7, 1, 11, Blocks.fence);
        world.setBlock(2, 1, 12, Blocks.fence);
        world.setBlock(6, 1, 12, Blocks.fence);
        world.setBlock(2, 2, 0, Blocks.fence);
        world.setBlock(6, 2, 0, Blocks.fence);
        world.setBlock(11, 2, 0, Blocks.fence);
        world.setBlock(1, 2, 1, Blocks.fence);
        world.setBlock(2, 2, 1, Blocks.planks);
        world.setBlock(3, 2, 1, Blocks.planks);
        world.setBlock(4, 2, 1, Blocks.glass);
        world.setBlock(5, 2, 1, Blocks.glass);
        world.setBlock(6, 2, 1, Blocks.planks);
        world.setBlock(7, 2, 1, Blocks.glass);
        world.setBlock(8, 2, 1, Blocks.glass);
        world.setBlock(9, 2, 1, Blocks.planks);
        world.setBlock(10, 2, 1, Blocks.planks);
        world.setBlock(2, 2, 2, Blocks.planks);
        world.setBlock(3, 2, 2, Blocks.bookshelf);
        world.setBlock(10, 2, 2, Blocks.glass);
        world.setBlock(2, 2, 3, Blocks.planks);
        world.setBlock(3, 2, 3, Blocks.wooden_pressure_plate);
        world.setBlock(10, 2, 3, Blocks.wooden_door);
        world.setBlockMetadataWithNotify(10, 2, 3, 9, 9);
        world.setBlock(2, 2, 4, Blocks.planks);
        world.setBlock(3, 2, 4, Blocks.stone_pressure_plate);
        world.setBlock(10, 2, 4, Blocks.wooden_door);
        world.setBlockMetadataWithNotify(10, 2, 4, 8, 8);
        world.setBlock(2, 2, 5, Blocks.planks);
        world.setBlock(3, 2, 5, Blocks.fence);
        world.setBlock(6, 2, 5, Blocks.redstone_torch);
        world.setBlockMetadataWithNotify(6, 2, 5, 5, 5);
        world.setBlock(9, 2, 5, Blocks.fence);
        world.setBlock(10, 2, 5, Blocks.glass);
        world.setBlock(2, 2, 6, Blocks.planks);
        world.setBlock(6, 2, 6, Blocks.planks);
        world.setBlock(7, 2, 6, Blocks.glass);
        world.setBlock(8, 2, 6, Blocks.glass);
        world.setBlock(9, 2, 6, Blocks.planks);
        world.setBlock(10, 2, 6, Blocks.planks);
        world.setBlock(2, 2, 7, Blocks.glass);
        world.setBlock(6, 2, 7, Blocks.glass);
        world.setBlock(11, 2, 7, Blocks.fence);
        world.setBlock(2, 2, 8, Blocks.glass);
        world.setBlock(6, 2, 8, Blocks.glass);
        world.setBlock(2, 2, 9, Blocks.planks);
        world.setBlock(3, 2, 9, Blocks.redstone_torch);
        world.setBlockMetadataWithNotify(3, 2, 9, 5, 5);
        world.setBlock(6, 2, 9, Blocks.planks);
        world.setBlock(2, 2, 10, Blocks.planks);
        world.setBlock(3, 2, 10, Blocks.glass);
        world.setBlock(4, 2, 10, Blocks.glass);
        world.setBlock(5, 2, 10, Blocks.glass);
        world.setBlock(6, 2, 10, Blocks.planks);
        world.setBlock(1, 2, 11, Blocks.fence);
        world.setBlock(7, 2, 11, Blocks.fence);
        world.setBlock(2, 2, 12, Blocks.fence);
        world.setBlock(6, 2, 12, Blocks.fence);
        world.setBlock(1, 3, 0, Blocks.stone_stairs);
        world.setBlock(2, 3, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(2, 3, 0, 2, 2);
        world.setBlock(3, 3, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(3, 3, 0, 2, 2);
        world.setBlock(4, 3, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(4, 3, 0, 2, 2);
        world.setBlock(5, 3, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(5, 3, 0, 2, 2);
        world.setBlock(6, 3, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(6, 3, 0, 2, 2);
        world.setBlock(7, 3, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(7, 3, 0, 2, 2);
        world.setBlock(8, 3, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(8, 3, 0, 2, 2);
        world.setBlock(9, 3, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(9, 3, 0, 2, 2);
        world.setBlock(10, 3, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(10, 3, 0, 2, 2);
        world.setBlock(11, 3, 0, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(11, 3, 0, 2, 2);
        world.setBlock(1, 3, 1, Blocks.stone_stairs);
        world.setBlock(2, 3, 1, Blocks.planks);
        world.setBlock(3, 3, 1, Blocks.planks);
        world.setBlock(4, 3, 1, Blocks.glass);
        world.setBlock(5, 3, 1, Blocks.glass);
        world.setBlock(6, 3, 1, Blocks.planks);
        world.setBlock(7, 3, 1, Blocks.glass);
        world.setBlock(8, 3, 1, Blocks.glass);
        world.setBlock(9, 3, 1, Blocks.planks);
        world.setBlock(10, 3, 1, Blocks.planks);
        world.setBlock(1, 3, 2, Blocks.stone_stairs);
        world.setBlock(2, 3, 2, Blocks.planks);
        world.setBlock(3, 3, 2, Blocks.bookshelf);
        world.setBlock(6, 3, 2, Blocks.torch);
        world.setBlockMetadataWithNotify(6, 3, 2, 3, 3);
        world.setBlock(9, 3, 2, Blocks.torch);
        world.setBlockMetadataWithNotify(9, 3, 2, 2, 2);
        world.setBlock(10, 3, 2, Blocks.planks);
        world.setBlock(1, 3, 3, Blocks.stone_stairs);
        world.setBlock(2, 3, 3, Blocks.planks);
        world.setBlock(3, 3, 3, Blocks.chest);
        world.setBlockMetadataWithNotify(3, 3, 3, 5, 5);
        world.setBlock(10, 3, 3, Blocks.planks);
        world.setBlock(1, 3, 4, Blocks.stone_stairs);
        world.setBlock(2, 3, 4, Blocks.planks);
        world.setBlock(3, 3, 4, Blocks.chest);
        world.setBlockMetadataWithNotify(3, 3, 4, 5, 5);
        world.setBlock(10, 3, 4, Blocks.planks);
        world.setBlock(1, 3, 5, Blocks.stone_stairs);
        world.setBlock(2, 3, 5, Blocks.planks);
        world.setBlock(3, 3, 5, Blocks.bookshelf);
        world.setBlock(6, 3, 5, Blocks.torch);
        world.setBlockMetadataWithNotify(6, 3, 5, 4, 4);
        world.setBlock(9, 3, 5, Blocks.fence);
        world.setBlock(10, 3, 5, Blocks.planks);
        world.setBlock(1, 3, 6, Blocks.stone_stairs);
        world.setBlock(2, 3, 6, Blocks.planks);
        world.setBlock(3, 3, 6, Blocks.torch);
        world.setBlockMetadataWithNotify(3, 3, 6, 1, 1);
        world.setBlock(6, 3, 6, Blocks.planks);
        world.setBlock(7, 3, 6, Blocks.glass);
        world.setBlock(8, 3, 6, Blocks.glass);
        world.setBlock(9, 3, 6, Blocks.planks);
        world.setBlock(10, 3, 6, Blocks.planks);
        world.setBlock(1, 3, 7, Blocks.stone_stairs);
        world.setBlock(2, 3, 7, Blocks.glass);
        world.setBlock(6, 3, 7, Blocks.glass);
        world.setBlock(7, 3, 7, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(7, 3, 7, 3, 3);
        world.setBlock(8, 3, 7, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(8, 3, 7, 3, 3);
        world.setBlock(9, 3, 7, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(9, 3, 7, 3, 3);
        world.setBlock(10, 3, 7, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(10, 3, 7, 3, 3);
        world.setBlock(11, 3, 7, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(11, 3, 7, 3, 3);
        world.setBlock(1, 3, 8, Blocks.stone_stairs);
        world.setBlock(2, 3, 8, Blocks.glass);
        world.setBlock(6, 3, 8, Blocks.glass);
        world.setBlock(7, 3, 8, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(7, 3, 8, 1, 1);
        world.setBlock(1, 3, 9, Blocks.stone_stairs);
        world.setBlock(2, 3, 9, Blocks.planks);
        world.setBlock(6, 3, 9, Blocks.planks);
        world.setBlock(7, 3, 9, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(7, 3, 9, 1, 1);
        world.setBlock(1, 3, 10, Blocks.stone_stairs);
        world.setBlock(2, 3, 10, Blocks.planks);
        world.setBlock(3, 3, 10, Blocks.glass);
        world.setBlock(4, 3, 10, Blocks.glass);
        world.setBlock(5, 3, 10, Blocks.glass);
        world.setBlock(6, 3, 10, Blocks.planks);
        world.setBlock(7, 3, 10, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(7, 3, 10, 1, 1);
        world.setBlock(1, 3, 11, Blocks.stone_stairs);
        world.setBlock(7, 3, 11, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(7, 3, 11, 1, 1);
        world.setBlock(2, 3, 12, Blocks.fence);
        world.setBlock(6, 3, 12, Blocks.fence);
        world.setBlock(2, 4, 1, Blocks.oak_stairs);
        world.setBlock(3, 4, 1, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(3, 4, 1, 2, 2);
        world.setBlock(4, 4, 1, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(4, 4, 1, 2, 2);
        world.setBlock(5, 4, 1, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(5, 4, 1, 2, 2);
        world.setBlock(6, 4, 1, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(6, 4, 1, 2, 2);
        world.setBlock(7, 4, 1, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(7, 4, 1, 2, 2);
        world.setBlock(8, 4, 1, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(8, 4, 1, 2, 2);
        world.setBlock(9, 4, 1, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(9, 4, 1, 2, 2);
        world.setBlock(10, 4, 1, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(10, 4, 1, 2, 2);
        world.setBlock(11, 4, 1, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(11, 4, 1, 2, 2);
        world.setBlock(2, 4, 2, Blocks.oak_stairs);
        world.setBlock(10, 4, 2, Blocks.glass);
        world.setBlock(2, 4, 3, Blocks.oak_stairs);
        world.setBlock(10, 4, 3, Blocks.glass);
        world.setBlock(2, 4, 4, Blocks.oak_stairs);
        world.setBlock(10, 4, 4, Blocks.glass);
        world.setBlock(2, 4, 5, Blocks.oak_stairs);
        world.setBlock(6, 4, 5, Blocks.bookshelf);
        world.setBlock(7, 4, 5, Blocks.chest);
        world.setBlockMetadataWithNotify(7, 4, 5, 2, 2);
        world.setBlock(8, 4, 5, Blocks.chest);
        world.setBlockMetadataWithNotify(8, 4, 5, 2, 2);
        world.setBlock(9, 4, 5, Blocks.bookshelf);
        world.setBlock(10, 4, 5, Blocks.glass);
        world.setBlock(2, 4, 6, Blocks.oak_stairs);
        world.setBlock(6, 4, 6, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(6, 4, 6, 3, 3);
        world.setBlock(7, 4, 6, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(7, 4, 6, 3, 3);
        world.setBlock(8, 4, 6, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(8, 4, 6, 3, 3);
        world.setBlock(9, 4, 6, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(9, 4, 6, 3, 3);
        world.setBlock(10, 4, 6, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(10, 4, 6, 3, 3);
        world.setBlock(11, 4, 6, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(11, 4, 6, 3, 3);
        world.setBlock(2, 4, 7, Blocks.oak_stairs);
        world.setBlock(6, 4, 7, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(6, 4, 7, 1, 1);
        world.setBlock(2, 4, 8, Blocks.oak_stairs);
        world.setBlock(6, 4, 8, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(6, 4, 8, 1, 1);
        world.setBlock(2, 4, 9, Blocks.oak_stairs);
        world.setBlock(3, 4, 9, Blocks.torch);
        world.setBlockMetadataWithNotify(3, 4, 9, 4, 4);
        world.setBlock(5, 4, 9, Blocks.torch);
        world.setBlockMetadataWithNotify(5, 4, 9, 4, 4);
        world.setBlock(6, 4, 9, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(6, 4, 9, 1, 1);
        world.setBlock(2, 4, 10, Blocks.oak_stairs);
        world.setBlock(3, 4, 10, Blocks.planks);
        world.setBlock(4, 4, 10, Blocks.planks);
        world.setBlock(5, 4, 10, Blocks.planks);
        world.setBlock(6, 4, 10, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(6, 4, 10, 1, 1);
        world.setBlock(2, 4, 11, Blocks.stone_stairs);
        world.setBlock(3, 4, 11, Blocks.stone_slab);
        world.setBlock(4, 4, 11, Blocks.stone_slab);
        world.setBlock(5, 4, 11, Blocks.stone_slab);
        world.setBlock(6, 4, 11, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(6, 4, 11, 1, 1);
        world.setBlock(2, 4, 12, Blocks.stone_slab);
        world.setBlock(3, 4, 12, Blocks.stone_slab);
        world.setBlock(4, 4, 12, Blocks.stone_slab);
        world.setBlock(5, 4, 12, Blocks.stone_slab);
        world.setBlock(6, 4, 12, Blocks.stone_slab);
        world.setBlock(3, 5, 2, Blocks.oak_stairs);
        world.setBlock(4, 5, 2, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(4, 5, 2, 2, 2);
        world.setBlock(5, 5, 2, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(5, 5, 2, 2, 2);
        world.setBlock(6, 5, 2, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(6, 5, 2, 2, 2);
        world.setBlock(7, 5, 2, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(7, 5, 2, 2, 2);
        world.setBlock(8, 5, 2, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(8, 5, 2, 2, 2);
        world.setBlock(9, 5, 2, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(9, 5, 2, 2, 2);
        world.setBlock(10, 5, 2, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(10, 5, 2, 2, 2);
        world.setBlock(11, 5, 2, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(11, 5, 2, 2, 2);
        world.setBlock(3, 5, 3, Blocks.oak_stairs);
        world.setBlock(4, 5, 3, Blocks.planks);
        world.setBlock(5, 5, 3, Blocks.planks);
        world.setBlock(6, 5, 3, Blocks.planks);
        world.setBlock(7, 5, 3, Blocks.planks);
        world.setBlock(8, 5, 3, Blocks.planks);
        world.setBlock(9, 5, 3, Blocks.planks);
        world.setBlock(10, 5, 3, Blocks.planks);
        world.setBlock(3, 5, 4, Blocks.oak_stairs);
        world.setBlock(4, 5, 4, Blocks.planks);
        world.setBlock(5, 5, 4, Blocks.planks);
        world.setBlock(6, 5, 4, Blocks.planks);
        world.setBlock(7, 5, 4, Blocks.planks);
        world.setBlock(8, 5, 4, Blocks.planks);
        world.setBlock(9, 5, 4, Blocks.planks);
        world.setBlock(10, 5, 4, Blocks.planks);
        world.setBlock(3, 5, 5, Blocks.oak_stairs);
        world.setBlock(4, 5, 5, Blocks.glass);
        world.setBlock(5, 5, 5, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(5, 5, 5, 1, 1);
        world.setBlock(6, 5, 5, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(6, 5, 5, 3, 3);
        world.setBlock(7, 5, 5, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(7, 5, 5, 3, 3);
        world.setBlock(8, 5, 5, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(8, 5, 5, 3, 3);
        world.setBlock(9, 5, 5, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(9, 5, 5, 3, 3);
        world.setBlock(10, 5, 5, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(10, 5, 5, 3, 3);
        world.setBlock(11, 5, 5, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(11, 5, 5, 3, 3);
        world.setBlock(3, 5, 6, Blocks.oak_stairs);
        world.setBlock(4, 5, 6, Blocks.glass);
        world.setBlock(5, 5, 6, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(5, 5, 6, 1, 1);
        world.setBlock(3, 5, 7, Blocks.oak_stairs);
        world.setBlock(4, 5, 7, Blocks.glass);
        world.setBlock(5, 5, 7, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(5, 5, 7, 1, 1);
        world.setBlock(3, 5, 8, Blocks.oak_stairs);
        world.setBlock(4, 5, 8, Blocks.glass);
        world.setBlock(5, 5, 8, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(5, 5, 8, 1, 1);
        world.setBlock(3, 5, 9, Blocks.oak_stairs);
        world.setBlock(4, 5, 9, Blocks.glass);
        world.setBlock(5, 5, 9, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(5, 5, 9, 1, 1);
        world.setBlock(3, 5, 10, Blocks.oak_stairs);
        world.setBlock(4, 5, 10, Blocks.planks);
        world.setBlock(5, 5, 10, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(5, 5, 10, 1, 1);
        world.setBlock(3, 5, 11, Blocks.stone_stairs);
        world.setBlock(4, 5, 11, Blocks.cobblestone);
        world.setBlock(5, 5, 11, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(5, 5, 11, 1, 1);
        world.setBlock(4, 6, 3, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(4, 6, 3, 2, 2);
        world.setBlock(5, 6, 3, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(5, 6, 3, 2, 2);
        world.setBlock(6, 6, 3, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(6, 6, 3, 2, 2);
        world.setBlock(7, 6, 3, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(7, 6, 3, 2, 2);
        world.setBlock(8, 6, 3, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(8, 6, 3, 2, 2);
        world.setBlock(9, 6, 3, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(9, 6, 3, 2, 2);
        world.setBlock(10, 6, 3, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(10, 6, 3, 2, 2);
        world.setBlock(11, 6, 3, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(11, 6, 3, 2, 2);
        world.setBlock(4, 6, 4, Blocks.oak_stairs);
        world.setBlock(5, 6, 4, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(5, 6, 4, 3, 3);
        world.setBlock(6, 6, 4, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(6, 6, 4, 3, 3);
        world.setBlock(7, 6, 4, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(7, 6, 4, 3, 3);
        world.setBlock(8, 6, 4, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(8, 6, 4, 3, 3);
        world.setBlock(9, 6, 4, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(9, 6, 4, 3, 3);
        world.setBlock(10, 6, 4, Blocks.oak_stairs);
        world.setBlockMetadataWithNotify(10, 6, 4, 3, 3);
        world.setBlock(11, 6, 4, Blocks.stone_stairs);
        world.setBlockMetadataWithNotify(11, 6, 4, 3, 3);

        return super.addComponentParts(world, random, structureBoundingBox);
    }
}
