// Date: 02/10/2016 11:37:49
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.shadcanard.fbm.models;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFemme extends ModelBiped
{
  //fields
    ModelRenderer BaseBig;
  
  public ModelFemme()
  {
    textureWidth = 64;
    textureHeight = 32;

      BaseBig = new ModelRenderer(this, 19, 21);
    BaseBig.mirror = true;
      BaseBig.addBox(-1F, -1F, -1F, 8, 3, 2);
      BaseBig.setRotationPoint(-3F, 4F, -2F);
      BaseBig.setTextureSize(64, 32);
      setRotation(BaseBig, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    BaseBig.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
